version: "3.9"

networks:
  banking-application-network:
    driver: bridge
    
services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BankingDB
    networks:
      - banking-application-network
    volumes:
      - bankingapplication-database-volume:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "localhost", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - banking-application-network
    restart: always
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status"]
        interval: 5s
        timeout: 20s
        retries: 5

volumes:
  bankingapplication-database-volume: