version: "3.9"

networks:
  bankingapplication_network:
    driver: bridge

services:
  banking_microservice:
    container_name: banking_micro
    build:
      context: .
      dockerfile: BankingDockerfile
    ports:
      - "81:80"
    networks: 
      - bankingapplication_network
    restart: always
    depends_on: 
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  transaction_microservice:
    container_name: transaction_micro
    build:
      context: .
      dockerfile: TransactionDockerfile
    ports:
      - "82:80"
    networks: 
      - bankingapplication_network
    restart: always
    depends_on: 
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BankingDatabase, TransactionDatabase
    networks:
      - bankingapplication_network
    volumes:
      - bankingapplication-postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "localhost", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_NODENAME: somenode@rabbitmq
    networks:
      - bankingapplication_network
    volumes:
      - bankingapplication-rabbitmq-data:/var/lib/rabbitmq/mnesia
    restart: always
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status"]
        interval: 5s
        timeout: 20s
        retries: 5

volumes:
  bankingapplication-postgres-data:
  bankingapplication-rabbitmq-data: